package test.gov.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 04 20:01:27 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RequestVOImpl() {
    }
}

