package test.gov.model;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 04 20:01:27 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        RequestId,
        RequestDesc,
        RequestLoc,
        RequestCode,
        LocationsVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int REQUESTDESC = AttributesEnum.RequestDesc.index();
    public static final int REQUESTLOC = AttributesEnum.RequestLoc.index();
    public static final int REQUESTCODE = AttributesEnum.RequestCode.index();
    public static final int LOCATIONSVO1 = AttributesEnum.LocationsVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RequestVORowImpl() {
    }
}

